services:
  postgres:
    image: postgres:15
    container_name: postgres-expense-tracker
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - expense-tracker-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-expense-tracker-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # This to override the DATABASE_URL in the app to link it with the db service
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
      - DATABASE_URL_ALEMBIC=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    networks:
      - expense-tracker-network
    command: >
      sh -c "
        . .venv/bin/activate &&
        alembic -x url=$${DATABASE_URL_ALEMBIC} upgrade head &&
        uv run run.py
      "


volumes:
  postgres_data:
    driver: local

networks:
  expense-tracker-network:
    driver: bridge