"""added constraint on FK and expense_participants_model

Revision ID: 24b06af8dd6b
Revises: 4d267a514c69
Create Date: 2025-08-03 16:52:50.928164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b06af8dd6b'
down_revision: Union[str, Sequence[str], None] = '4d267a514c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group_participation')
    )
    op.create_unique_constraint('uq_group_expense_payer', 'expenses', ['group_id', 'payer_id'])
    op.create_unique_constraint(None, 'expenses', ['id'])
    op.create_unique_constraint('uq_group_user_membership', 'group_members', ['group_id', 'user_id'])
    op.create_unique_constraint(None, 'group_members', ['id'])
    op.drop_constraint(op.f('groups_name_key'), 'groups', type_='unique')
    op.create_unique_constraint(None, 'groups', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique') # type: ignore 
    op.create_unique_constraint(op.f('groups_name_key'), 'groups', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'group_members', type_='unique') # type: ignore 
    op.drop_constraint('uq_group_user_membership', 'group_members', type_='unique')
    op.drop_constraint(None, 'expenses', type_='unique') # type: ignore 
    op.drop_constraint('uq_group_expense_payer', 'expenses', type_='unique')
    op.drop_table('expense_participants')
    # ### end Alembic commands ###
