"""reoved the payer unique constraint in expense model

Revision ID: 334aee256479
Revises: e44aff2e6b8b
Create Date: 2025-08-04 16:20:57.134903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334aee256479'
down_revision: Union[str, Sequence[str], None] = 'e44aff2e6b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_group_expense_payer'), 'expenses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_group_expense_payer'), 'expenses', ['group_id', 'payer_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
