"""fixed user relations

Revision ID: dcdd9e141e38
Revises: 24b06af8dd6b
Create Date: 2025-08-03 17:56:52.256809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdd9e141e38'
down_revision: Union[str, Sequence[str], None] = '24b06af8dd6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_participants', sa.Column('expense_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_user_group_participation'), 'expense_participants', type_='unique')
    op.create_unique_constraint('uq_user_expense_participation', 'expense_participants', ['user_id', 'expense_id'])
    op.drop_constraint(op.f('expense_participants_group_id_fkey'), 'expense_participants', type_='foreignkey')
    op.create_foreign_key(None, 'expense_participants', 'expenses', ['expense_id'], ['id'])
    op.drop_column('expense_participants', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_participants', sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expense_participants', type_='foreignkey')
    op.create_foreign_key(op.f('expense_participants_group_id_fkey'), 'expense_participants', 'groups', ['group_id'], ['id'])
    op.drop_constraint('uq_user_expense_participation', 'expense_participants', type_='unique')
    op.create_unique_constraint(op.f('uq_user_group_participation'), 'expense_participants', ['user_id', 'group_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('expense_participants', 'expense_id')
    # ### end Alembic commands ###
