"""FIXED ON DELETE CASCADE

Revision ID: e44aff2e6b8b
Revises: dcdd9e141e38
Create Date: 2025-08-04 10:33:21.016234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44aff2e6b8b'
down_revision: Union[str, Sequence[str], None] = 'dcdd9e141e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expense_participants_user_id_fkey'), 'expense_participants', type_='foreignkey')
    op.drop_constraint(op.f('expense_participants_expense_id_fkey'), 'expense_participants', type_='foreignkey')
    op.create_foreign_key(None, 'expense_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'expense_participants', 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('expenses_payer_id_fkey'), 'expenses', type_='foreignkey')
    op.drop_constraint(op.f('expenses_group_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'expenses', 'users', ['payer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('groups_created_by_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_created_by_fkey'), 'groups', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_group_id_fkey'), 'expenses', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(op.f('expenses_payer_id_fkey'), 'expenses', 'users', ['payer_id'], ['id'])
    op.drop_constraint(None, 'expense_participants', type_='foreignkey')
    op.drop_constraint(None, 'expense_participants', type_='foreignkey')
    op.create_foreign_key(op.f('expense_participants_expense_id_fkey'), 'expense_participants', 'expenses', ['expense_id'], ['id'])
    op.create_foreign_key(op.f('expense_participants_user_id_fkey'), 'expense_participants', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
